'use strict';

var nicePhrases = ["If you want to achieve greatness stop asking for permission. ~Anonymous",
"Things work out best for those who make the best of how things work out. ~John Wooden",
"To live a creative life, we must lose our fear of being wrong. ~Anonymous", 
"If you are not willing to risk the usual you will have to settle for the ordinary. ~Jim Rohn"
,"Trust because you are willing to accept the risk, not because it’s safe or certain. ~Anonymous",
"Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda",
"All our dreams can come true if we have the courage to pursue them. ~Walt Disney", 
"Good things come to people who wait, but better things come to those who go out and get them. ~Anonymous",
"If you do what you always did, you will get what you always got. ~Anonymous", 
"Success is walking from failure to failure with no loss of enthusiasm. ~Winston Churchill",
"Just when the caterpillar thought the world was ending, he turned into a butterfly. ~Proverb", 
"Successful entrepreneurs are givers and not takers of positive energy. ~Anonymous",
"Whenever you see a successful person you only see the public glories, never the private sacrifices to reach them. ~Vaibhav Shah", 
"Don’t be afraid to give up the good to go for the great. ~John D. Rockefeller",
"The distance between insanity and genius is measured only by success. ~Bruce Feirstein",
"Don’t raise your voice, improve your argument. ~Anonymous","What seems to us as bitter trials are often blessings in disguise.~ Oscar Wilde",
"What seems to us as bitter trials are often blessings in disguise.~ Oscar Wilde",
"Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. ~Nathaniel Hawthorne",
"Do one thing every day that scares you. ~Anonymous","What’s the point of being alive if you don’t at least try to do something remarkable. ~Anonymous",
"Life is not about finding yourself. Life is about creating yourself. ~Lolly Daskal",
"Knowledge is being aware of what you can do. Wisdom is knowing when not to do it. ~Anonymous",
"Innovation distinguishes between a leader and a follower. ~Steve Jobs","You can do anything, but not everything. ~Anonymous",
"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. ~Ray Goforth",
"Success is most often achieved by those who don't know that failure is inevitable. - Coco Chanel",
"Things work out best for those who make the best of how things work out. - John Wooden",
"Courage is grace under pressure. - Ernest Hemingway",
"If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
"Learn from yesterday, live for today, hope for tomorrow. The important thing is not to stop questioning. - Albert Einstein",
"Take up one idea. Make that one idea your life - think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body be full of that idea, and just leave every other idea alone. This is the way to success. - Swami Vivekananda",
"Sometimes you can't see yourself clearly until you see yourself through the eyes of others. - Ellen DeGeneres",
"All our dreams can come true if we have the courage to pursue them. - Walt Disney",
"It does not matter how slowly you go, so long as you do not stop. - Confucius",
"Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
"Someone is sitting in the shade today because someone planted a tree a long time ago. - Warren Buffett",
"Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them. - Vaibhav Shah",
"Don't cry because it's over, smile because it happened. - Dr. Seuss",
"Success? I don't know what that word means. I'm happy. But success, that goes back to what in somebody's eyes success means. For me, success is inner peace. That's a good day for me. - Denzel Washington",
"You only live once, but if you do it right, once is enough. - Mae West",
"Opportunities don't happen. You create them. - Chris Grosser",
"Once you choose hope, anything's possible. - Christopher Reeve",
"Try not to become a person of success, but rather try to become a person of value. - Albert Einstein",
"There is no easy walk to freedom anywhere, and many of us will have to pass through the valley of the shadow of death again and again before we reach the mountaintop of our desires. - Nelson Mandela",
"It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change. - Charles Darwin",
"The best and most beautiful things in the world cannot be seen or even touched -- they must be felt with the heart. - Helen Keller",
"Great minds discuss ideas; average minds discuss events; small minds discuss people. - Eleanor Roosevelt",
"Live as if you were to die tomorrow. Learn as if you were to live forever. - Mahatma Gandhi",
"The best revenge is massive success. - Frank Sinatra",
"The difference between winning and losing is most often not quitting. - Walt Disney",
"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
"When you cease to dream you cease to live. - Malcolm Forbes",
"A successful man is one who can lay a firm foundation with the bricks others have thrown at him. - David Brinkley",
"May you live every day of your life. - Jonathan Swift",
"No one can make you feel inferior without your consent. - Eleanor Roosevelt",
"Failure is another steppingstone to greatness. - Oprah Winfrey",
"The whole secret of a successful life is to find out what is one's destiny to do, and then do it. - Henry Ford",
"If you're not stubborn, you'll give up on experiments too soon. And if you're not flexible, you'll pound your head against the wall and you won't see a different solution to a problem you're trying to solve. - Jeff Bezos",
"If you're going through hell, keep going. - Winston Churchill",
"In order to be irreplaceable one must always be different. - Coco Chanel",
"”What seems to us as bitter trials are often blessings in disguise. - Oscar Wilde",
"You miss 100 percent of the shots you don't take. - Wayne Gretzky",
"The distance between insanity and genius is measured only by success. - Bruce Feirstein",
"The way I see it, if you want the rainbow, you gotta put up with the rain. - Dolly Parton",
"To me, business isn't about wearing suits or pleasing stockholders. It's about being true to yourself, your ideas and focusing on the essentials. - Richard Branson",
"The longer I live, the more beautiful life becomes. - Frank Lloyd Wright",
"Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you. - Nathaniel Hawthorne",
"You must expect great things of yourself before you can do them. - Michael Jordan",
"If you can't explain it simply, you don't understand it well enough. - Albert Einstein",
"You can't please everyone, and you can't make everyone like you. - Katie Couric",
"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed. - Ray Goforth",
"I believe every human has a finite number of heartbeats. I don't intend to waste any of mine. - Neil Armstrong",
"Start where you are. Use what you have. Do what you can. - Arthur Ashe",
"Don't limit yourself. Many people limit themselves to what they think they can do. You can go as far as your mind lets you. What you believe, remember, you can achieve. - Mary Kay Ash",
"People ask, 'What's the best role you've ever played?' The next one. - Kevin Kline",
"The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
"I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
"It often requires more courage to dare to do right than to fear to do wrong. - Abraham Lincoln",
"Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
"As you grow older, you will discover that you have two hands, one for helping yourself, the other for helping others. - Audrey Hepburn",
"If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work. - Thomas J. Watson",
"If your actions inspire others to dream more, learn more, do more, and become more, you are a leader. - John Quincy Adams",
"All progress takes place outside the comfort zone. - Michael John Bobak",
"The more you praise and celebrate your life, the more there is in life to celebrate. - Oprah Winfrey",
"You may only succeed if you desire succeeding; you may only fail if you do not mind failing. - Philippos",
"A dream doesn't become reality through magic; it takes sweat, determination, and hard work. - Colin Powell",
"Only put off until tomorrow what you are willing to die having left undone. - Pablo Picasso",
"The biggest risk is not taking any risk... In a world that's changing really quickly, the only strategy that is guaranteed to fail is not taking risks. - Mark Zuckerberg",
"We become what we think about most of the time, and that's the strangest secret. - Earl Nightingale",
"Do one thing every day that scares you. - Eleanor Roosevelt",
"The only place where success comes before work is in the dictionary. - Vidal Sassoon",
"Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
"Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle. As with all matters of the heart, you'll know when you find it.--Steve Jobs",
"Don't worry about failure; you only have to be right once. - Drew Houston",
"Though no one can go back and make a brand-new start, anyone can start from now and make a brand-new ending. - Carl Bard",
"Nothing great was ever achieved without enthusiasm. - Ralph Waldo Emerson",
"Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover. - Mark Twain",
"Keep your face to the sunshine and you can never see the shadow. - Helen Keller",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. - Mark Caine",
"One of the greatest diseases is to be nobody to anybody. - Mother Teresa",
"Identity is a prison you can never escape, but the way to redeem your past is not to run from it, but to try to understand it, and use it as a foundation to grow. - Jay-Z",
"The successful warrior is the average man, with laser-like focus. - Bruce Lee",
"Rarely have I seen a situation where doing less than the other guy is a good strategy. - Jimmy Spithill",
"If you always do what interests you, at least one person is pleased. - Katharine Hepburn",
"Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down. - Charles F. Kettering",
"I avoid looking forward or backward, and try to keep looking upward. - Charlotte Bronte",
"You can't connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. - Steve Jobs",
"Life is short, and it is here to be lived. - Kate Winslet",
"Everything you can imagine is real. - Pablo Picasso",
"Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek. - Barack Obama",
"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! - T. Harv Eker",
"Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
"It is never too late to be what you might have been. - George Eliot",
"If you love what you do and are willing to do what it takes, it's within your reach. And it'll be worth every minute you spend alone at night, thinking and thinking about what it is you want to design or build. - Steve Wozniak",
"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. - Jane Smiley",
"In the midst of movement and chaos, keep stillness inside of you. - Deepak Chopra",
"Success does not consist in never making mistakes but in never making the same one a second time. - George Bernard Shaw",
"I don't want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. - Diane Ackerman",
"As we look ahead into the next century, leaders will be those who empower others. - Bill Gates",
"As we look ahead into the next century, leaders will be those who empower others. - Bill Gates","The only place where success comes before work is in the dictionary. ~Vidal Sassoon",
"The best reason to start an organization is to make meaning; to create a product or service to make the world a better place. ~Guy Kawasaki",
"I find that when you have a real interest in life and a curious life, that sleep is not the most important thing. ~Martha Stewart",
"It’s not what you look at that matters, it’s what you see. ~Anonymous",
"The road to success and the road to failure are almost exactly the same. ~Colin R. Davis",
"The function of leadership is to produce more leaders, not more followers. ~Ralph Nader",
"Success is liking yourself, liking what you do, and liking how you do it. ~Maya Angelou",
"As we look ahead into the next century, leaders will be those who empower others. ~Bill Gates",
"A real entrepreneur is somebody who has no safety net underneath them. ~Henry Kravis",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself. ~Mark Caine",
"People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy. ~Tony Robbins",
"When I dare to be powerful - to use my strength in the service of my vision, then it becomes less and less important whether I am afraid. ~Audre Lorde",
"Whenever you find yourself on the side of the majority, it is time to pause and reflect. ~Mark Twain",
"The successful warrior is the average man, with laser-like focus. ~Bruce Lee",
"Take up one idea. Make that one idea your life — think of it, dream of it, live on that idea. Let the brain, muscles, nerves, every part of your body, be full of that idea, and just leave every other idea alone. This is the way to success. ~Swami Vivekananda",
"Develop success from failures. Discouragement and failure are two of the surest stepping stones to success. ~Dale Carnegie",
"If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. ~ Jim Rohn",
"If you genuinely want something, don’t wait for it — teach yourself to be impatient. ~Gurbaksh Chahal",
"Don’t let the fear of losing be greater than the excitement of winning. ~Robert Kiyosaki",
"If you want to make a permanent change, stop focusing on the size of your problems and start focusing on the size of you! ~T. Harv Eker",
"You can’t connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future. You have to trust in something - your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life. ~Steve Jobs",
"Successful people do what unsuccessful people are not willing to doDon’t wish it were easier, wish you were better. ~Jim Rohn",
"The number one reason people fail in life is because they listen to their friends, family, and neighbors. ~Napoleon Hill",
"The reason most people never reach their goals is that they don’t define them, or ever seriously consider them as believable or achievable. Winners can tell you where they are going, what they plan to do along the way, and who will be sharing the adventure with them. ~Denis Watiley",
"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it. ~Jane Smiley",
"Success does not consist in never making mistakes but in never making the same one a second time. ~George Bernard Shaw",
"I don’t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well. ~Diane Ackerman",
"You must expect great things of yourself before you can do them. ~Michael Jordan",
"Motivation is what gets you started. Habit is what keeps you going. ~Jim Ryun",
"People rarely succeed unless they have fun in what they are doing. ~Dale Carnegie",
"There is no chance, no destiny, no fate, that can hinder or control the firm resolve of a determined soul. ~Ella Wheeler Wilcox",
"Our greatest fear should not be of failure but of succeeding at things in life that don’t really matter. ~Francis Chan",
"You’ve got to get up every morning with determination if you’re going to go to bed with satisfaction. ~George Lorimer",
"To be successful you must accept all challenges that come your way. You can’t just accept the ones you like. ~Mike Gafka",
"Success is...knowing your purpose in life, growing to reach your maximum potential, and sowing seeds that benefit others. ~ John C. Maxwell",
"Be miserable. Or motivate yourself. Whatever has to be done, it’s always your choice. ~Wayne Dyer",
"To accomplish great things, we must not only act, but also dream, not only plan, but also believe.~ Anatole France",
"Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no help at all. ~Dale Carnegie",
"You measure the size of the accomplishment by the obstacles you had to overcome to reach your goals. ~Booker T. Washington",
"Real difficulties can be overcome; it is only the imaginary ones that are unconquerable. ~Theodore N. Vail",
"It is better to fail in originality than to succeed in imitation. ~Herman Melville",
"Fortune sides with him who dares. ~Virgil",
"Little minds are tamed and subdued by misfortune; but great minds rise above it. ~Washington Irving",
"Failure is the condiment that gives success its flavor. ~Truman Capote",
"Don’t let what you cannot do interfere with what you can do. ~John R. Wooden",
"You may have to fight a battle more than once to win it. ~Margaret Thatcher",
"You may have to fight a battle more than once to win it. ~Margaret Thatcher"

];

// Get random phrase
var random = nicePhrases[Math.floor(Math.random() * nicePhrases.length)];
// console.log(random);

document.getElementById("rathernice").textContent = random.toString();